name: pathsight
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - xarray
  - shapely
  - pillow
  - aom>=3.11
  - libopenblas
  - openssl
  - ca-certificates
  - pip:
    # Add any pip-only packages here if needed